<a href="https://colab.research.google.com/github/tejsvinimeshram/Practical/blob/main/EE524_task2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# upload dataset

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving RSS - Original.csv to RSS - Original (1).csv

# load dataset

In [ ]:
df=pd.read_csv('RSS - Original.csv')
df.head()

   X  Y  RSS - A  RSS - B  RSS - C
0  6  2       37       58       68
1  2  2       47       63       73
2  2  6       51       54       73
3  5  6       53       52       74
4  5  9       62       52       65

# check dataset

In [ ]:
print(df.shape)
print(df.columns)
df.info()
df.describe()

(24, 5)
Index(['X', 'Y', 'RSS - A', 'RSS - B', 'RSS - C'], dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   X        24 non-null     int64
 1   Y        24 non-null     int64
 2   RSS - A  24 non-null     int64
 3   RSS - B  24 non-null     int64
 4   RSS - C  24 non-null     int64
dtypes: int64(5)
memory usage: 1.1 KB

               X          Y    RSS - A    RSS - B    RSS - C
count  24.000000  24.000000  24.000000  24.000000  24.000000
mean    3.416667  18.541667  61.666667  61.375000  58.916667
std     2.041241   9.055285   9.581080   7.400426   9.357242
min     0.000000   2.000000  37.000000  39.000000  45.000000
25%     1.750000  11.250000  58.000000  58.000000  50.000000
50%     3.500000  20.000000  62.000000  62.500000  57.500000
75%     5.000000  25.250000  65.750000  66.000000  66.500000
max     6.000000  30.000000  82.000000  73.000000  74.000000

# handle missing values

In [ ]:
df = pd.read_csv('RSS - Original.csv')
df.isnull().sum()
df=df.dropna()

# select features and target

In [ ]:
x=df[['X','Y']]
y=df['RSS - A']
#or use only Distance if applicable.

# Train test split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

# Train Model

In [ ]:
model=LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

# load features and target

In [ ]:
X=df[['X','Y']]
Y=df[['RSS - A','RSS - B','RSS - C']]

# Train-Test Split

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

# Train Model

In [ ]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, Y_train)

LinearRegression()

# Perediction

In [ ]:
y_pred = model.predict(X_test)

# Evalution

In [ ]:
from sklearn.metrics import (
    mean_squared_error,
    r2_score,
    mean_absolute_error
)
import numpy as np

print(f"Mean Absolute Error: {mean_absolute_error(Y_test, y_pred)}")
print(f"Root Mean Squared Error: {np.sqrt(mean_squared_error(Y_test, y_pred))}")
print(f"R-squared: {r2_score(Y_test, y_pred)}")

Mean Absolute Error: 4.871763234024626
Root Mean Squared Error: 6.178441066302545
R-squared: -0.48447434144451784

# predict New Location

In [ ]:
new_location_data = pd.DataFrame([[4, 3]], columns=['X', 'Y'])
pred = model.predict(new_location_data)
print(pred)

[[52.85955747 52.27004527 71.63198431]]

# Actual VS Predicted

In [ ]:
resuit=pd.DataFrame({'Actual RSS-A':Y_test['RSS - A'].values,
                     'Predicted RSS-A': y_pred[:,0],
                     'Actual RSS-B': Y_test['RSS - B'].values,
                     'Predicted RSS-B': y_pred[:,1],
                     'Actual RSS-C': Y_test['RSS - C'].values,
                     'Predicted RSS-C': y_pred[:,2]})